name: 'Slack messaging'
description: 'Send and update slack messages'

inputs:
  token:
    description: Slack Bot token (beginning with xoxb-)
    required: true

  channel:
    description: What channel to send the message to
    required: false

  message:
    description: 'The message to show'
    required: false

  context:
    description: 'The status message'
    required: false

  message_id:
    description: 'The message_id to update'
    required: false

outputs:
  message_id:
    description: 'The channel name and timestamp, comma separated'

runs:
  using: 'node12'
  main: 'dist/index.js'
