---
name: Send test message on push

on:
  push

jobs:
  send:
    runs-on: ubuntu-20.04
    steps:
      - name: Test SlackAction
        id: slack_init
        uses: placo-ab/slack-api-action@master
        with:
          token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          message: This is a text!
          context: Waiting...
          channel: UQUQZFTS6

      - name: Wait 10s...
        run: sleep 10

      - name: Update message
        uses: placo-ab/slack-api-action@master
        with:
          token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          message: This is another text!
          context: Not waiting any more!
          message_id: ${{ steps.slack_init.outputs.message_id }}
